# Generated by Django 4.1.3 on 2023-07-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogpost', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='default_foo.png', upload_to='post_picture'),
        ),
    ]
