# Generated by Django 4.1.3 on 2023-07-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogpost', '0003_post_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default_foo.jpg', upload_to='post_img'),
        ),
    ]
